name: Build and deploy ASP.Net Core app to Azure App Service

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore C:\Own\Szakdolgozat\8.0\CampaignManager\CampaignManager.sln

      - name: Build Web project
        run: dotnet build C:\Own\Szakdolgozat\8.0\CampaignManager\CampaignManager.Web\CampaignManager.Web.csproj --configuration Release

      - name: Build WebAPI project
        run: dotnet build C:\Own\Szakdolgozat\8.0\CampaignManager\CampaignManager.WebAPI\CampaignManager.WebAPI.csproj --configuration Release

      - name: Publish Web project
        run: dotnet publish C:\Own\Szakdolgozat\8.0\CampaignManager\CampaignManager.Web\CampaignManager.Web.csproj --configuration Release --output C:\Own\Szakdolgozat\8.0\CampaignManager\publish\CampaignManager.Web

      - name: Publish WebAPI project
        run: dotnet publish C:\Own\Szakdolgozat\8.0\CampaignManager\CampaignManager.WebAPI\CampaignManager.WebAPI.csproj --configuration Release --output C:\Own\Szakdolgozat\8.0\CampaignManager\publish\CampaignManager.WebAPI

      - name: Upload Web project artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-app
          path: C:\Own\Szakdolgozat\8.0\CampaignManager\publish\CampaignManager.Web

      - name: Upload WebAPI project artifact
        uses: actions/upload-artifact@v3
        with:
          name: webapi-app
          path: C:\Own\Szakdolgozat\8.0\CampaignManager\publish\CampaignManager.WebAPI

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Web project artifact
        uses: actions/download-artifact@v3
        with:
          name: web-app
          path: C:\Own\Szakdolgozat\8.0\CampaignManager\publish\CampaignManager.Web

      - name: Download WebAPI project artifact
        uses: actions/download-artifact@v3
        with:
          name: webapi-app
          path: C:\Own\Szakdolgozat\8.0\CampaignManager\publish\CampaignManager.WebAPI

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Web project to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: C:\Own\Szakdolgozat\8.0\CampaignManager\publish\CampaignManager.Web

      - name: Deploy WebAPI project to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: C:\Own\Szakdolgozat\8.0\CampaignManager\publish\CampaignManager.WebAPI
